# 未対応、可変的なルールを記述 
inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  
AllCops:
  # Rubyのバージョンを指定 
  TargetRubyVersion: 2.6
  
  # 除外ディレクトリ
  Exclude:
    - bin/*
    - db/schema.rb
    - vendor/**/*
  
# "Method has too many lines"を無視
Metrics/MethodLength:
  Enabled: false
  
# "Block has too many lines"を無視(rspecテストのため)
Metrics/BlockLength:
  Enabled: false
  
# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false
  
# ブロックコメントを許可  
Style/BlockComments:
  Enabled: false
  

# 文字列のfreeze要求を無視
Style/FrozenStringLiteralComment:
  Enabled: false
  
# "Line is too long"を無視
Layout/LineLength:
  Enabled: false
  
# "Prefer single-quoted strings when you don't need string interpolation or special symbols"を無視
Style/StringLiterals:
  Enabled: false

# "Missing top-level class documentation comment"を無視
Style/Documentation:
  Enabled: false
  
# Gemfileのアルファベット順記入を無視  
Bundler/OrderedGems:  
  Enabled: false
  
# ネストしたモジュール/クラス定義の推奨記法を無視
Style/ClassAndModuleChildren:
  Enabled: false

# "Specify an :inverse_of option"を無視
Rails/InverseOf:
  Enabled: false
  
# Rubocopの最新の検知ルールはtrueにする
Layout/SpaceAroundMethodCallOperator:
  Enabled:  true
  
Lint/RaiseException:
  Enabled:  true
  
Lint/StructNewOverride:
  Enabled:  true
  
Style/ExponentialNotation:
  Enabled:  true  
  
Style/HashTransformKeys:
  Enabled:  true
  
Style/HashTransformValues:
  Enabled:  true
  
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
  
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
  
Lint/MixedRegexpCaptureTypes:
  Enabled: true
  
Style/AccessorGrouping:
  Enabled: true
  
Style/BisectedAttrAccessor:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true
  
Style/RedundantFetchBlock:
  Enabled: true
  
Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true
  
# 例外的にfalseとする。capistranoのconfig:displayにて異常検知されるため
Style/HashEachMethods:
  Enabled:  false
  
# デバッグ用のputsが異常検知されるため、falseとする
Rails/Output:
  Enabled: false

# update_attributeの使用を許可
Rails/SkipsModelValidations:
  Enabled: false
  
# includeのファイル冒頭以外での使用を許可
Style/MixinUsage:
  Enabled: false
  
# Class has too many linesを無視
Metrics/ClassLength:
  Enabled: false

