# 未対応のルールを記述 
inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  
AllCops:
  # Rubyのバージョンを指定 
  TargetRubyVersion: 2.6
  
  # 除外ディレクトリ
  Exclude:
    - bin/*
    - db/schema.rb
    - vendor/**/*
  
# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false
  
# ブロックコメントを許可  
Style/BlockComments:
  Enabled: false
  
# 文字列のfreeze要求を無視
Style/FrozenStringLiteralComment:
  Enabled: false
  
# "Line is too long"を無視
Layout/LineLength:
  Enabled: false
  
# "Prefer single-quoted strings when you don't need string interpolation or special symbols"を無視
Style/StringLiterals:
  Enabled: false

# "Missing top-level class documentation comment"を無視
Style/Documentation:
  Enabled: false
  
# Gemfileのアルファベット順記入を無視  
Bundler/OrderedGems:  
  Enabled: false
  
# ネストしたモジュール/クラス定義の推奨記法を無視
ClassAndModuleChildren:
  Enabled: false
  