# circleciのバージョン
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6-node-browsers
        environment:
          RAILS_ENV: test
          MYSQL_HOST: 127.0.0.1
          
      - image: mysql:5.7.28
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: root
          
    # 並列実行するコンテナ数。無料プランでは1しか指定できない
    parallelism: 1
    
    # 作業ディレクトリを指定
    working_directory: ~/sample
    
    steps:
      # CI環境上のworking_directoryの場所にgitリポジトリをコピーする
      - checkout
      
      # bundle install高速化のため、キャッシュを利用
      - restore_cache:
          keys:
            - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rails-demo-bundle-v2-
      
      # gemのインストールを行う
      - run:
          name: gem install
          command: bundle install --jobs=4 --retry=3
          
      # キャッシュを保存する
      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/.bundle
      
      # mysqlの起動待機
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      
      # DB再起動
      #- run:
      #    name: restart DB
      #    command: sudo service mysqld restart
      
      - run: bundle exec rails db:create
      - run: bundle exec rails db:schema:load --trace
      
      - run:
          name: Which bundler?
          command: bundle -v
      
      #- run:
      #    name: rubocop
      #    command: bundle exec rubocop
