development:
  #adapter: async
  adapter: redis
  port: 6379
  url: redis://localhost
  channel_prefix: sample_development

test:
  #adapter: async
  adapter: <%= ENV.fetch("TEST_ADAPTER") { async } %>
  #adapter: redis
  #port: 6379
  #url: redis://localhost
  channel_prefix: sample_test

production:
  adapter: redis
  port: 6379
  url: redis://localhost
  channel_prefix: sample_production