development:
  adapter: redis
  port: 6379
  url: redis://localhost
  channel_prefix: sample_development

test:
  # 開発EC2ではredisを使用し、circleci上ではasyncを使用する
  adapter: <%= ENV.fetch("TEST_ADAPTER") { "async" } %>
  port: <%= ENV.fetch("TEST_PORT") { } %>
  url: <%= ENV.fetch("TEST_URL") { } %>
  channel_prefix: sample_test

production:
  adapter: redis
  port: 6379
  url: redis://localhost
  channel_prefix: sample_production
